### ISSUE TITLE
Key error 44 when using 'poker_ai play' command

### ISSUE THREAD

**Issue by jaimeggb** [fedden/poker_ai#154]
**Describe the bug**

The problem seems to be something to do with the line `offline_strategy_dict = joblib.load(strategy_path)`, which is midway through the console print shown below.

```bash
(base) jupyter@tensorflow-2-8-20221021-201315:~/poker_ai$ poker_ai play --lut_path /home/jupyter/poker_ai/research/blueprint_algo --strategy_path /home/jupyter/poker_ai/research/blueprint_algo/_2022_10_19_20_44_25_523196/agent.joblib --pickle_dir False --agent offline
[10:00:54] INFO     Loading card from single file at path: /home/jupyter/poker_ai/research/blueprint_algo                                            state.py:280
Traceback (most recent call last):
  File "/opt/conda/bin/poker_ai", line 6, in <module>
    cli()
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/poker_ai/terminal/runner.py", line 65, in run_terminal_app
    offline_strategy_dict = joblib.load(strategy_path) ### <<<-----------------------------------------------------------------
  File "/opt/conda/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 658, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/opt/conda/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 577, in _unpickle
    obj = unpickler.load()
  File "/opt/conda/lib/python3.7/pickle.py", line 1088, in load
    dispatch[key[0]](self)
KeyError: 44
```

**To Reproduce**
1. Go to path 'poker_ai'
2. Run command 'poker_ai play --lut_path /home/jupyter/poker_ai/research/blueprint_algo --strategy_path /home/jupyter/poker_ai/research/blueprint_algo/_2022_10_19_20_44_25_523196/agent.joblib --pickle_dir False --agent offline'
3. See error

**Comment by meisken** [comment]
I got the same error, Did you find any solution?
